# Generated by Django 2.2.8 on 2020-09-05 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='password',
            field=models.CharField(default=' ', max_length=32),
        ),
    ]
